server:
  port: 8001

spring:
  application:
    name: discord-gateway
  main:
    web-application-type: reactive
    #允许存在多个Feign调用相同Service的接口
    allow-bean-definition-overriding: true
  cloud:
    nacos:
      server-addr: http://192.168.200.199:8848
    gateway:
      globalcors: # 全局的跨域处理
        add-to-simple-url-handler-mapping: true # 解决options请求被拦截问题
        corsConfigurations:
          '[/**]':
            allowedOrigins: # 允许哪些网站的跨域请求
              - "*"
            allowedMethods: # 允许的跨域ajax的请求方式
              - "GET"
              - "POST"
              - "DELETE"
              - "PUT"
              - "OPTIONS"
            allowedHeaders: "*" # 允许在请求中携带的头信息
#            allowCredentials: true # 是否允许携带cookie
            maxAge: 360000 # 这次跨域检测的有效期
      routes:
        - id: discord-user  # 路由id 自定义 只要唯一即可
          uri: lb://discord-user  # 路由的目标地址 lb 是负载均衡 后面是服务名称
          predicates:  # 路由断言 判断请求是否符合路由规则的条件
            - Path=/user/**
